storyblok/storyblok-nuxt:
  - source: .github/ISSUE_TEMPLATE
    template:
      tech:
        name: "Nuxt 3"
        package: "nuxt"

storyblok/storyblok-vue:
  - source: .github/ISSUE_TEMPLATE
    template:
      tech:
        name: "Vue 3"
        package: "vue"

storyblok/storyblok-nuxt-2:
  - source: .github/ISSUE_TEMPLATE
    template:
    tech:
      name: "Nuxt 2"
      package: "nuxt"

storyblok/storyblok-vue-2:
  - source: .github/ISSUE_TEMPLATE
    template:
      tech:
        name: "Vue 2"
        package: "vue"

storyblok/storyblok-react:
  - source: .github/ISSUE_TEMPLATE
    template:
      tech:
        name: "React"
        package: "react"

storyblok/gatsby-source-storyblok:
  - source: .github/ISSUE_TEMPLATE
    template:
      tech:
        name: "Gatsby"
        package: "gatsby"

storyblok/storyblok-svelte:
  - source: .github/ISSUE_TEMPLATE
    template:
      tech:
        name: "Svelte"
        package: "svelte"

storyblok/storyblok-astro:
  - source: .github/ISSUE_TEMPLATE
    template:
      tech:
        name: "Astro"
        package: "astro"
